# Generated by Django 3.2.16 on 2022-11-03 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone_num', models.IntegerField()),
                ('dob', models.DateTimeField(auto_now_add=True)),
                ('house_name', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('medicine', models.CharField(max_length=50)),
            ],
        ),
    ]
